import typing
from xander.engine.actors import Stats
from xander.engine.combat.arena import Arena, ProtoArena
from xander.engine.combat.turn import Turn

class Combatant:
    @property
    def name(self) -> str: ...

    @property
    def position(self) -> tuple[float, float, float]: ...

    @property
    def stats(self) -> Stats: ...

    @property
    def initiative(self) -> int: ...

    def observe(self) -> list[int]: ...

    def __repr__(self) -> str: ...

    def __eq__(self, value): ...

type CombatantHook = typing.Callable[[Turn], typing.Any]

class Combat:
    # TODO: add ordering=None to the signature !
    def __init__(self, arena: ProtoArena): ...

    @property
    def arena(self) -> Arena: ...

    def join(self, monster: Stats, name: str, position: tuple[float, float, float], hook: CombatantHook) -> Combatant: ...

    def step(self) -> None: ...

    def __repr__(self) -> str: ...

    def _repr_html_(self) -> str: ...

    @property
    def current(self) -> Combatant: ...

    @property
    def combatants(self) -> list[Combatant]: ...

    def __len__(self) -> int: ...

    @property
    def rounds(self) -> int: ...

