from typing import Literal, Optional
from xander.engine.combat.action import Action
from xander.engine.damage import Damage

class Attack(Action):
    def __repr__(self): ...
    def _repr_html_(self): ...

    @property
    def type(self) -> Literal["melee", "ranged"]: ...

    @property
    def name(self) -> str: ...

class AttackResult:
    @property
    def successful(self) -> bool: ...
    
    @property
    def to_hit(self) -> AttackRoll: ...
    
    @property
    def damage(self) -> Optional[Damage]: ...

class AttackRoll:
    def __repr__(self) -> str: ...