from typing import Optional


class Legality[T]:
    def is_legal(self) -> bool: ...

    def is_illegal(self) -> bool: ...

    def inner(self) -> Optional[T]: ...

    def __repr__(self) -> str: ...