#[derive(Debug, Clone, Copy)]
pub struct Strength;
#[derive(Debug, Clone, Copy)]
pub struct Dexterity;
#[derive(Debug, Clone, Copy)]
pub struct Constitution;
#[derive(Debug, Clone, Copy)]
pub struct Intelligence;
#[derive(Debug, Clone, Copy)]
pub struct Wisdom;
#[derive(Debug, Clone, Copy)]
pub struct Charisma;
